set -ga terminal-overrides ",screen-256color*:Tc"
set-option -g default-terminal "screen-256color"
set -s escape-time 0

set -g status-style 'bg=default fg=cyan'

set -g base-index 1
set-option -g set-clipboard on

