exec-once = systemctl --user start hyprpolkitagent
exec-once = nm-applet
exec-once = swww-daemon
exec-once = ~/scripts/set_wallpaper.sh
exec-once = waybar

exec-once = [workspace 1 silent] alacritty
exec-once = [workspace 2 silent] zen-browser

