exec-once = systemctl --user start hyprpolkitagent

exec-once = swww-daemon
exec-once = exec ~/scripts/set_wallpaper.sh

exec-once = hyprsunset -t 4000

exec-once = nm-applet

exec-once = fcitx5 -dr

exec-once = [workspace 1 silent] alacritty
exec-once = [workspace 2 silent] zen-browser
